import bz2
from pathlib import Path

from PIL import Image
import base64
from io import BytesIO

input_logo: str = 'logo-1024x991.png'
new_width: int = 200
output_file = 'logo.css'

image = Image.open(input_logo)
width = image.size[0]
height = image.size[1]
new_height: int = int(new_width * height / width)
image = image.resize((new_width, new_height))
buffered = BytesIO()
image.save(buffered, format='png', optimize=True, quality=95)
base64_image = base64.b64encode(buffered.getvalue())

with open(output_file, 'wt') as f:
    f.write(
        f'/*\n'
        f'############################################################################\n'
        f'# This file is generated by {Path(__file__).name}, DO NOT EDIT !!!\n'
        f'############################################################################\n'
        f'*/\n'
        f'\n'
        f'body {{\n'
        f'\tbackground-image: url("data:image/png;base64,{base64_image.decode("utf-8")}");\n'
        f'\tbackground-attachment: fixed;\n'
        f'\tbackground-position: right top;\n'
        f'\tbackground-repeat:no-repeat;\n'
        f'}}\n')
print(f'Wrote {output_file}.')
